### ISSUE TITLE
open source

### ISSUE THREAD

**Issue by manuel76413** [zdenyhraz/IPC#1]
The program runs excellently, that's amazing.

Would you prepare to share the source code on Github?
That will be helpful:-)

**Comment by zdenyhraz** [comment]
I'm curious, what's your usecase? Do you need subpixel precision?

**Comment by manuel76413** [comment]
> I'm curious, what's your usecase? Do you need subpixel precision?

Yes, I think IPC can be used in  panorama image generating, based on many photos of the same scene,
or it can be used in image patch search.

I'm not sure if the small image patch is from a different camera with a different focus, different zoom ratio, and rotated or sometimes with projective transform, compared to the big image, does IPC works OK?

**Comment by zdenyhraz** [comment]
The IPC can do translation and rotation/zoom, but not projective transform

**Comment by zdenyhraz** [comment]
I updated the readme with a link to the source code.
